# Generated by Django 4.2.1 on 2023-07-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contacts',
        ),
    ]
