# Generated by Django 4.2.1 on 2023-06-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='email',
            new_name='emailAddress',
        ),
    ]
