# Generated by Django 4.2.1 on 2023-06-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_rename_email_vendor_emailaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='emailAddress',
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email Address'),
            preserve_default=False,
        ),
    ]
