# Generated by Django 4.2.1 on 2023-06-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_remove_vendor_emailaddress_vendor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(max_length=32),
        ),
    ]
