# Generated by Django 4.2.1 on 2023-06-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=32)),
                ('placement', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(max_length=32)),
                ('number_of_orders', models.PositiveIntegerField()),
                ('total_amount', models.PositiveIntegerField()),
            ],
        ),
    ]
