# Generated by Django 4.2.1 on 2023-07-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
        ('Shipment_Management', '0001_initial'),
        ('purchases', '0002_orders_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cart',
            field=models.ManyToManyField(to='Cart.basket'),
        ),
        migrations.AddField(
            model_name='orders',
            name='shipment',
            field=models.ManyToManyField(to='Shipment_Management.shipment'),
        ),
    ]
