# Generated by Django 4.2.1 on 2023-07-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('total', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('shipping_cost', models.FloatField()),
                ('discounts', models.FloatField()),
                ('products', models.ManyToManyField(to='inventory.product')),
            ],
        ),
    ]
